Expensify/Bedrock-PHP

bin/BedrockWorkerManager.php, composer.json
@flodnv please review. /cc @coleaeason 
Needed for https://github.com/Expensify/Expensify/issues/40404
Web and Salt PRs incoming. We can merge this anyway, since no one will be using this version of the lib.
Tests:
- Invoke bwm without the versionWatchFile param. Check it works.
- Invoke bwm with the versionWatchFile param:
- Check it works if the file doesn't exist.
- Check that it stops processing new jobs when the file time changes.
- Check that it waits till all processing jobs finish before dying.
- Bonus feature: You can now stop bwm on dev with CTRL+C 😄
=> Support bwm stop processing new jobs when a file changes

composer.json, src/Exceptions/Jobs/RetryableException.php
The type for `$message` should be a string, not int.
=> Fix param type

composer.json, src/Jobs.php
@iwiznia Please review these changes.
Added additional params to `queueJob` and `createJob` to allow setting the `'Connection'` header.
Reference: https://github.com/Expensify/Web-Expensify/pull/16198#discussion_r98462964
Tested with changes in https://github.com/Expensify/Web-Expensify/pull/16198
1. Uploaded Square receipt into dev.
2. After parsing completed, changed the category from Uncategorized to a category that has a mapped MCC in the policy settings.
3. Confirmed www-prod/UpdateMerchantToMCCUsage was queued in the jobs table and returned `202` code success code.
=> Allow setting of connection header for queueJob

bin/BedrockWorkerManager.php, composer.json, package.sh
This will allow us to catch php errors that go uncatched now, like [this one](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:("vqgsba")+AND+timestamp:[2017-02-01T14:41:16.679Z+TO+2017-02-01T16:41:16.679Z]&index=logs_2017-02-01)
Tests:
In BWM we log the exception as a param, since the LoggerInterface doesn't have `->exception` as a method like `Log` does.
```
$caca = null;
try {
$caca->caca();
} catch (Throwable $e) {
Log::alert('Yay!', ['error' => $e]);
}
```
Log:
```
Feb 17 15:50:46 vagrant-ubuntu-trusty-64 php-cgi: wmNorj /caca.php ionatan@expensify.com !web! ?api? [alrt] Yay! ~~ error: 'Error: Call to a member function caca() on null in /vagrant/Web-Expensify/caca.php:7#012Stack trace:#012#0 {main}'
```
=> Catch throwable

bin/BedrockWorkerManager.php, composer.json
Issue: https://github.com/Expensify/Expensify/issues/47084
We added `writeConsistency` as a config option but didn't added it to the command line options.
=> Add writeConsistency as a command line param

bin/BedrockWorkerManager.php, composer.json, src/Client.php
By having a circular reference between `Client` and its plugins, PHP can't free the objects, thus leaking sockets. This is not a big problem for web requests, since they are short lived, but it is for long running processes that instantiate many `Client` objects.
/cc @cead22
=> Prevent leak

bin/BedrockWorkerManager.php, composer.json, sample/SampleWorker.php, sample/demo.sh, sample/test.sh, src/Client.php, src/Jobs.php
This does the following:
1. Adds a simple script that demonstrates Bedrock::Jobs with a trivial worker.
2. Includes a few minor internal cleanups, with comments on each inside the diff.
3. Provides a new API to fix https://github.com/Expensify/Expensify/issues/50199 (see https://github.com/Expensify/Web-Expensify/pull/17025)
4. Fixes https://github.com/Expensify/Expensify/issues/50137
Sorry for globbing multiple issues and cleanups into a single PR; I wanted to use the demo harness I built to solve those other issues.
Assigning to @iwiznia for review this and https://github.com/Expensify/Web-Expensify/pull/17025
=> Add simple demo framework for Bedrock::Jobs; add requestID; add retries

bin/BedrockWorkerManager.php
Fixes https://github.com/Expensify/Expensify/issues/50915#issuecomment-297441035
Tests:
---
First I updated my quick randotest.php file to generate old and new REQUEST_IDs, and included my filter:
```
avids-MacBook-Pro:~ dbarrett$ cat randotest.php 
<?php
// Original function
function originalGenerateID() {static $alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";mt_srand();$id = '';for ($i = 0; $i < 6; $i++) {$id .= $alphabet[mt_rand(0, strlen($alphabet) - 1)];}return $id;}
// Current function
function currentGenerateID() {
return substr(base64_encode(sha1(strval(mt_rand()), true)), 0, 6); // random 6 character ID
}
// New function
function newGenerateID() {
return substr(str_replace(['+','/'], '', base64_encode(openssl_random_pseudo_bytes(6))), 0, 6); // random …
```
=> Remove + and / from REQUEST_ID

composer.json, src/Jobs.php
@iwiznia please review
When calling `CreateJob`, set `idempotent` based on `$unique`. This will allow any request that failed due a `ConnectionFailure` to be automatically retried if `$unique = true`.
Given that when creating jobs with `$unique = true`, Bedrock returns data about any existing job with the same name if it exists, there's no risk to accidentally create another job with the same name.
=> Use idempotent parameter for CreateJob

composer.json, src/DB.php
cc @cead22 
Let's append `;` to a query if it does not exist
This is needed for https://github.com/Expensify/Bedrock/pull/215
=> Append a semicolon to queries if none exists

bin/BedrockWorkerManager.php, composer.json
**Problem**
BWM-PHP kicks off multiple forks of itself to connect to bedrock to query for work (the query itself is blocking - when BWM has a job ready, it’ll then respond to the request).
We have a substantial amount of jobs that are queued to be worked on, and they cannot all kick off at once or else we will effectively DDOS ourselves.
**Solution**
Use a command-line argument that caps the number of forks that can exist at any moment to a configurable number.
**Tests**
1. Create 10 jobs with a 5 second sleep.
2. Run bwm with `--maxNumberWorkerThreads=1`
3. Tail logs, confirm number of worker threads is never above 1.
4. Repeat steps 1-3 with `--maxNumberWorkerThreads=5`.
=> Temporary BWM load handler

bin/BedrockWorkerManager.php, composer.json
The `intval` call was preventing the null coalescing operator from properly setting the default value
1. Create 10 jobs with a 5 second sleep.
1. Run bwm with --maxNumberWorkerThreads=4
- Tail logs, confirm number of worker threads is never above 4 (search for `Load is`) and there are no notices referencing `maxNumberWorkerThreads`
1. Repeat steps 1-2 without a default
- Tail logs, confirm that the number of worker threads is never over the default (5) and there are no notices referencing `maxNumberWorkerThreads`
=> Use intval after the null coalescing operator so the default can be properly set

bin/BedrockWorkerManager.php, composer.json
The return value for safeToStartNewJob needs to be an array with two values in it and for some reason I made it false and it made it through all the review. 😓 
Fixes https://github.com/Expensify/Expensify/issues/59055
Fixes https://github.com/Expensify/Expensify/issues/59057
Run bedrockWorkerManager without `--enableLoadHandler` and confirm it runs without error.
=> Fix return value for safeToStartNewJob

composer.json, src/Client.php
@flodnv please review. /cc @tylerkaraszewski 
Related to https://github.com/Expensify/Expensify/issues/59222#issuecomment-320674382
Add more logs to find out what happens when bedrock returns an invalid response.
=> Log full response body when length differs

bin/BedrockWorkerManager.php, composer.json
Another hotfix for bedrock worker manager.
1. Queue a bunch of jobs
2. Tail logs and grep "numActive"
3. run BedrockWorkerManager with `--enableLoadHandler` flag
4. Confirm in the logs that numActive fluctuates.
=> Add enableLoadHandler to inner function

bin/BedrockWorkerManager.php, composer.json
This PR introduces a few potential performance improvements for the BWM load handler.
1. Only open/close the connection if the load handler is enabled.
2. Enable WAL mode on the database. This is persistent so should only have to happen on DB creation.
3. Create an index on the `localJobID` if one doesn't exist already.
1. Delete localJobsDB.sql if it exists.
2. Queue test jobs
3. Run BWM with load handler enabled.
4. Confirm that there are no errors.
5. Open up `/tmp/localJobsDB.sql` and run `PRAGMA journal_mode;` and confirm the output is `wal`.
6. Run `.schema localJobs` and confirm the output is
```
CREATE TABLE localJobs (
localJobID integer PRIMARY KEY AUTOINCREMENT NOT NULL,
pid integer NOT NULL,
jobID integer NOT NULL,
jobName text NOT NULL,
started text NOT NULL,
ended text
); …
```
=> Add potential performance improvements for BWM load handler

bin/BedrockWorkerManager.php, composer.json
Due to poor testing on my part, this snuck through and was crashing BWM when the load handler wasn't enabled. This just makes sure the localDB object is defined.
Fixes https://github.com/Expensify/Expensify/issues/59896
1. Delete localJobsDB.sql if it exists.
2. Queue test jobs
3. Run BWM with load handler enabled.
4. Confirm that there are no errors.
5. Open up `/tmp/localJobsDB.sql` and run `PRAGMA journal_mode;` and confirm the output is `wal`.
6. Run `.schema localJobs` and confirm the output is
```
CREATE TABLE localJobs (
localJobID integer PRIMARY KEY AUTOINCREMENT NOT NULL,
pid integer NOT NULL,
jobID integer NOT NULL,
jobName text NOT NULL,
started text NOT NULL,
ended text
);
CREATE INDEX idx ON localJobs (localJobID);
```
1. Queue test jobs
2. Run BWM with load handler disabled …
=> Move creation of localDB object out of if statement to satisfy strict typing

composer.json, src/Jobs.php
@mattabullock please review.
Some commands don't return either name nor jobID and this fails when that happens.
=> Prevent error jobID

bin/BedrockWorkerManager.php, composer.json, src/LocalDB.php
The local SQLite DB is having locking issues so when it runs into an error we'll log the error and retry.
Related to https://github.com/Expensify/Expensify/issues/60379#issuecomment-325038663
1. Queue a million jobs
2. Run bwm with enableLoadHandler
3. Wait forever
4. `grep 'database is locked' syslog` and confirm that it doesn't appear
5. `grep 'Query failed, retrying' syslog` and confirm that it does appear
6. Run bwm without enableLoadHandler
7. Confirm everything runs with no errors.
=> Catch localJobsDB sqlite exception and retry immediately

bin/BedrockWorkerManager.php, composer.json, src/Client.php, src/Exceptions/Jobs/RetryableException.php, src/Jobs.php
Giving this to Chirag to complete over the next few days since I'll be out.
I hate that the order of parameters for `RetryableException` doesn't make any sense, but I don't want to change it so we can be backwards compatible.  
We can create another exception type so the that order of parameters makes more sense, but that doesn't seem worth it.
I didn't update the package version yet, I'll wait for the review before doing that
Closes https://github.com/Expensify/Expensify/issues/59735
- Create a job, retry it with changing it's name, confirm the name was changed
```
>>> use Expensify\Bedrock\Client;use Expensify\Bedrock\DB;use Expensify\Bedrock\Jobs;$c = new Client(); $jobs = new Jobs($c);$db = new DB($c)
=> Expensify\Bedrock\DB {#395}
>>> $jobs->createJob('foo')
=> [
"codeLine" => "200 …
```
=> Add options to change name and nextRun in retryJob

README.md, composer.json, src/Jobs.php
@iwiznia, will you please review this?
The `405` response code is not specific to jobs in the `RUNNING` state anymore, therefore we shouldn't say so on the PHP layer.
=> Fix IllegalAction exception message being wrongly specific

bin/BedrockWorkerManager.php, composer.json, src/Jobs.php
@mea36 
cc @iwiznia 
Fixes: https://github.com/Expensify/Expensify/issues/63406
Removes unused timeout parameter. This is a problem as we now have a global `timeout` for all commands in bedrock. I'm aware there's an issue to bring back the previous version of `timeout`, but we'll need to do so with a different name.
=> Remove unused timeout parameter

composer.json, src/Jobs.php
Part of the backend change needed to include `retryAfter` for the createJob.
Related to fixing issue - https://github.com/Expensify/Expensify/issues/53817
1. Copy the changes over to `Web-Expensify/vendor/expensify/Bedrock-PHP/src/Jobs.php`.
2. In psysh.sh run the following,
```
>>> use Expensify\Bedrock\Client;use Expensify\Bedrock\DB;use Expensify\Bedrock\Jobs;$c = new Client(); $jobs = new Jobs($c);$db = new DB($c)
=> Expensify\Bedrock\DB {#427}
>>> $jobs->createJob('testJob', null, null, null, false, 500, null, 'wait', '+1 hour');
[
"headers" => [
"commitCount" => "52552",
"nodeName" => "bedrock",
"peekTime" => "98",
"processTime" => "3588",
"totalTime" => "8033",
"Content-Length" => "19",
],
"body" => [
"jobID" => 222198170,
],
"size" => 138,
"codeLine" => "200 OK",
"code" => 200,
] …
```
=> Code to add retryAfter as the param for createJob

bin/BedrockWorkerManager.php, composer.json
When BWM unfortunately gets stuck in the safeToStartJob (because of stuck jobs in the localJobsDB) the version watch file doesn't currently work, so I added a check in the loop to make sure it can still shut down properly when it's stuck in that loop.
Fixes https://github.com/Expensify/Expensify/issues/64494
1. Run BWM with loadHandlerEnabled so it creates localJobsDB.sql
2. Fill the localJobsDB.sql with 10 dummy jobs with no closed date
3. Run BWM again with jobs queued, note that it keeps failing to start a job
4. `touch` the restart file, make sure it restarts correctly.
=> Check for version file change in the safeToStartJob loop

bin/BedrockWorkerManager.php, composer.json
We want a better log line for when there are more running jobs than max jobs so we can accurately track when we're being throttled by AIMD.
1. Create 30 jobs
2. Set ended to null in the last 10
3. Run BWM with `--enableLoadHandler`
4. Look for this line in the logs:
```
Nov  2 21:14:52 vagrant-ubuntu-trusty-64 php: s7W5Q4 vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] Not queueing job, number of running jobs is above the target ~~ numActive: '10' target: '10'
```
=> Add log line for when running jobs over target

bin/BedrockWorkerManager.php, composer.json
@mattabullock 
cc @iwiznia 
See https://github.com/Expensify/Expensify/issues/65705 -- logs are throwing `Argument 2 passed to safeToStartANewJob() must be of the type integer, float given, called in /git/expensify.com/vendor/expensify/Bedrock-PHP/bin/BedrockWorkerManager.php on line 129'`. This is the only place I could find that doesn't return an int (funnily enough, `floor` does not return an `int`) 
Not tested. LMK if this is right, and we can build the package.
=> Ensure safeToStartANewJob returns an int as the target

composer.json, src/DB/Response.php
Needed for https://github.com/Expensify/Web-Expensify/pull/19213
Tests:
- Call getRows with no param, check results are returned the same as before.
- Call getRows with true as a param, check the results are returned keyed by column.
=> Allow db results to be returned as associative arrays with column names as keys

composer.json, src/Client.php
@iwiznia , will you please review this?
This PR adds the number of retries the bedrock client is allotted to connect to the server as a configuration options.
Fixes https://github.com/Expensify/Expensify/issues/64873 and https://github.com/Expensify/Expensify/issues/65058
Note, the remaining phan errors are a bug with phan. I believe they can be ignored.
Also note, that the there is an accompanying [web pr](https://github.com/Expensify/Web-Expensify/pull/19151).
None
None
=> Add connection retries as configuration option to bedrock client

bin/BedrockWorkerManager.php, composer.json
Doing individual `GetJob` calls is causing too much synchronous time on the network, so we're attempting to optimize out the network time by returning multiple jobs every time with `GetJobs`.
1. Queue tons of jobs
2. Run BWM
3. Look for this log line
```
vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] Safe to start new job ~~ numberOfJobsToQueue: '1' numActive: '13' target: '14'
vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] Safe to start new job ~~ numberOfJobsToQueue: '1' numActive: '14' target: '15'
vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] Safe to start new job ~~ numberOfJobsToQueue: '1' numActive: '15' target: '16'
vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] Safe to start new job …
```
=> Use GetJobs instead of GetJob

bin/BedrockWorkerManager.php, composer.json
Two things here:
1. Change it to use microtime instead of SQL DATETIME - datetime has terrible accuracy, only down to the second. Most of our jobs take less than a second, so that's not super helpful.
2. Calculate the average time outside of SQL - Turns out when you limit by target but do a SUM in sqlite, it still sums everything, disregarding the limit completely. 
1. Queue tons of jobs
2. Check DB
3. Verify jobs are now shown as floats in the db
```
sqlite> SELECT started, ended FROM localJobs WHERE ended IS NOT NULL ORDER BY ended DESC LIMIT 10;
1511223595.47|1511223596.49
1511223595.29|1511223596.31
1511223595.44|1511223595.47
...
```
4. Verify jobs still queue correctly.
=> Change BWM queries to work more effectively

bin/BedrockWorkerManager.php, composer.json, src/Client.php, src/Jobs.php
Fixes https://github.com/Expensify/Expensify/issues/66144
This introduces socket reutilization to the bedrock Client class. In order to support being used in a multi threaded environment, like in BWM, it stores the sockets per pid, cluster and host name.
/cc @quinthar
=> Reuse sockets

bin/BedrockWorkerManager.php, composer.json
Please don't merge without letting me create a new release first. Maybe we could make it part of the approval process to have the approver package it? I dunno, just a thought. Makes it so we'd have fewer of the awful conflicts that people have with the versions.
---
Huge oversight in the recent GetJobs PR... forgot to make BWM read the parameter at all, so it just defaulted to 10. This is fine right now because we're just testing with the default, but obviously we'd like to be able to change it.
1. Queue 15 jobs
2. Run BWM with `--maxJobsInSingleRun=15 --minSafeJobs=15`
3. Confirm that the first run through AIMD shows this log line:
```
[info] Safe to start new job ~~ numberOfJobsToQueue: '15' numActive: '0' target: '15'
```
=> Fix new maxJobsInSingleRun param

composer.json, src/Client.php
@flodnv please review. DO NOT merge, I need to create the tag.
Context https://expensify.slack.com/archives/C0BS1NT42/p1512049104000222
Tests:
Before:
```
>>>  $logger = new Expensify\Logger();                                                                                                                                                                                                                                        => Expensify\Logger {#379}
>>>         $client = Expensify\Bedrock\Client::getInstance([                                                                                                                                                                                                                             'clusterName' => 'auth', …
```
=> Fix getInstance to not use the logger and stats params

bin/BedrockWorkerManager.php, composer.json
I added trackers into BWM and found that sometimes the inserts happen after the next call of GetJobs happens, sometimes causing us to queue more jobs than we're supposed to. Here I'm making the `insert` synchronous so we never queue more than allowed by AIMD.
```
Dec  4 23:55:11 vagrant-ubuntu-trusty-64 php: R7rPW1 vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] TRACKER START: 9
Dec  4 23:55:11 vagrant-ubuntu-trusty-64 php: xb5Q4w vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] TRACKER: 9
Dec  4 23:55:11 vagrant-ubuntu-trusty-64 php: 5jcpKx vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] TRACKER: 2
Dec  4 23:55:11 vagrant-ubuntu-trusty-64 php: NJpkEG vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] …
```
=> Make localJobs insert synchronous

bin/BedrockWorkerManager.php, composer.json, src/Client.php
Related https://github.com/Expensify/Expensify/issues/65544
I had one queued job that when it run, it created a new job. You can see how the commitCount from GetJobs is used for the CreateJob command and the commitCount of that is used for the FinishJob command:
```
Dec  8 16:24:19 vagrant-ubuntu-trusty-64 php: xZMKv0 vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [dbug] Bedrock\Client - Constructed ~~ clusterName: 'webrock' mainHostConfigs: '[localhost: '[port: '8888']']' failoverHostConfigs: '[localhost: '[port: '8888']']'
Dec  8 16:24:19 vagrant-ubuntu-trusty-64 php: xZMKv0 vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] Bedrock\Client - Starting a request ~~ command: 'GetJobs' clusterName: 'webrock' headers: '[name: …
```
=> Make bwm use commitCount from the parent in the children

bin/BedrockWorkerManager.php, composer.json, src/LocalDB.php
Hold for packaging.
I added timers that get sent to StatsD to help us evaluate how well BWM is performing.
Related: https://github.com/Expensify/Expensify/issues/61961
* Full loop (excluding GetJobs)
* CheckVersionFile
* GetNumberOfJobsToQueue
* Insert into localJobsDB
* Read from localJobsDB
* Delete from localJobsDB
* Update localJobsDB
* Fork
* Opening the DB
* Closing the DB
* Target
1. Run BWM with --enableLoadHandler and make sure it runs with no warns or errors.
No QA
=> Add timers for different parts of BWM process

bin/BedrockWorkerManager.php, composer.json
Needed for https://github.com/Expensify/Expensify/issues/69511
Tested by throwing manually right after `$this->receiveResponse()` in `Client` with code similar to (adapting the method for each test):
```
if ($hostName === 'localhost' && $method === 'FinishJob') {
$response = null;
throw new BedrockError('Pepe');
}
```
I have `localhost` as the main host and `127.0.0.1` as failover, so this means it will fail the first time (but after actually running the command) and retry.
Finishing a normal job:
```
Bedrock\Client - Starting a request ~~ command: 'FinishJob' clusterName: 'webrock' headers: '[jobID: '8540' data: '[]' idempotent: '1' commitCount: '18459' requestID: 'XtAf8Z' lastIP: '' writeConsistency: 'ASYNC']'
Bedrock\Client - APC fetch host configs ~~ 0: 'localhost' 1: '127.0.0.1' …
```
=> Do not fail BWM if we retried a command

bin/BedrockWorkerManager.php, composer.json
Emails have special characters in them, and it was allowing us to sql inject ourselves in the BWM db.
Related to: https://github.com/Expensify/Expensify/issues/66022
HOLD for updating version
1. Queue job with special characters in the params (i.e. `www-prod/TestJob?asdf=''''`)
2. Run BWM
3. Confirm that it doesn't crash and is inserted into the db effectively.
```
3|66|www-prod/TestJob?asdf=''''f'|1520450955.5|1520450955.62
```
=> Protect against sql injecting ourselves

composer.json, src/Cache.php
@fnwbr please review.
Tests:
- We have some automated tests in the web repo.
- Tested:
```
➜  Web-Expensify git:(staging) ✗ ../script/psysh.sh
Psy Shell v0.8.1 (PHP 7.0.28-1+ubuntu14.04.1+deb.sury.org+1 — cli) by Justin Hileman
New version is available (current: v0.8.1, latest: v0.8.17)
>>> $c = new Expensify\Bedrock\Cache(Expensify\Bedrock\Client::getInstance())
=> Expensify\Bedrock\Cache {#388}
>>> $c->write('something', '["uno"]')
=> [
"headers" => [
"Content-Length" => "0",
],
"body" => [],
"size" => 46,
"codeLine" => "202 Successfully queued",
"code" => 202,
]
>>> $c->read('something')
=> [
"headers" => [
"commitCount" => "19",
"name" => "something/",
"nodeName" => "bedrock",
"peekTime" => "3764",
"totalTime" => "3874",
"unaccountedTime" => "80",
"Content-Length" => "7",
],
"body" => …
```
=> Instrument cache

composer.json, src/Client.php
Tests:
With this auth config:
```
define('AUTH_HOSTS', ['auth' => ['port' => 4444]]);
define('AUTH_FAILOVERS', ['auth' => ['port' => 4444], 'localhost' => ['port' => 4444]]);
```
and this script:
```
Auth::call('Get', ['returnValueList' => 'account', 'authToken' => $authToken]);
Auth::call('SetNameValuePair', ['name' => 'caca', 'value' => 'caca', 'authToken' => $authToken, 'host' => 'localhost']);
Auth::call('Get', ['returnValueList' => 'account', 'authToken' => $authToken]);
```
Check that it used the correct host for each request (so, first `auth`, then `localhost`, then `auth` again). And check the `commitCount` was preserved across calls.
```
Apr 10 14:01:51 vagrant-ubuntu-trusty-64 php-cgi: xA82YN /caca.php ionatan@expensify.com !web! ?api? [dbug] …
```
=> Allow to pass preferred host

composer.json, src/DB.php
@mea36 please review.
Related https://github.com/Expensify/Expensify/issues/77283
Tests:
```
$db = new Expensify\Bedrock\DB(Expensify\Bedrock\Client::getInstance());
try {
$db->run('seleCt * fRom something as algo where a = 1', true);
} catch (Throwable $e) {}
try {
$db->run('select a,b,c fRom something as algo inner join other on algo.a = other.b where a = 1', true);
} catch (Throwable $e) {}
try {
$db->run('SELECT distinct a.a fRom something as algo inner join other on algo.a = other.b where a = 1 order by a group by c offset 1 limit 10;', true);
} catch (Throwable $e) {}
try {
$db->run('INSERT into table (one, two, three) VALUES (1,2,3), (3,4,5);', true);
} catch (Throwable $e) {}
try {
$db->run('UPDATE table set algo = 1, other = "string" WHERE field=true limit 100;', true);
} catch …
```
=> Track stats for db plugin

bin/BedrockWorkerManager.php, composer.json
Fixes https://github.com/Expensify/Expensify/issues/77430
We use GetJobs to try to dequeue several jobs in the same call, but since we are calling it immediately after starting all jobs, we usually end up retrieving very few jobs per call because the jobs did not have time to finish yet. By adding a sleep we hope to make the GetJobs calls to retrieve more jobs per run, which in turn reduces the possibilities of the command conflicting.
=> Sleep after starting some jobs

composer.json, src/Client.php
@mattabullock please review. This broke pinning hosts, aka setting the main/failover config to the same arrays, then having a preferred host come back that is not in those configs. We would then return a host with no port, which resulted in an error when the client tried to reconnect to the preferred host.
=> Fix preferred host when host doesn't exist in the configs

composer.json
This adds 1.4.6 at the head of master, because 1.4.5 was accidentally pointing at an older commit.
=> build version 1.4.6

.php_cs, .travis.yml, bin/BedrockWorkerManager.php, composer.json, composer.lock, src/Client.php, src/Jobs.php
Needed to fix this specific instance  https://github.com/Expensify/Expensify/issues/88302#issuecomment-429371913
Hold on https://github.com/Expensify/Bedrock/pull/514
Tests:
- Create a job without having done any bedrock call in any cluster. Check it created a job without adding any commitCounts.
- Create a job having done a call in only one cluster. Check it created the job and commitCounts contains only the count for that one cluster.
- Create a job having done a call in more than one cluster. Check it created the job and commitCounts contains all the counts for the clusters.
- Run BWM on the jobs created above and check that they correctly pass the commitCount (note: the webrock commitCount is updated again [here](https://github.com/Expensify/Bedrock-PHP/blob/1236fe20c4c3b82cbb50a56d67d …
=> Add commitCount to all updateJob and createJob data

bin/BedrockWorkerManager.php, src/Jobs.php
@tylerkaraszewski after talking with @quinthar we decided to rename the `commitCount` data to `_commitCount` to indicate that it is an internal property used by bedrock. We are really breaking the encapsulation (`data` should belong to the consumer) with this change, but is better than the alternative (add a new column in the jobs table to save that information).
Merge this before creating your version for the timeout change, then your version will already include this (that's why I did not create a version in this PR)
=> Prefix commitCount with _ to indicate internal property

composer.json, src/Client.php
@iwiznia 
Fixes: https://github.com/Expensify/Expensify/issues/90348
This sets the default timeout for a bedrock command to be just short of the socket timeout. This overrides the default 30 second timeout in bedrock.
Makes tag ~1.4.9 1.5.0~ 1.5.1 to use in web.
(I am bad at making tags after things are done)
I tested this by doing the following:
Edit `BedrockCore::peekCommand` to always throw `STHROW("555 Timeout")`. This means every command will timeout. I verified that the PHP Client throws a `ConnectionFailure` by loading the dev website and inspecting the logs.
For the normal case, using an unedited Bedrock, I loaded the dev website and watched the logs and saw:
```
2018-10-16T17:39:46.768988+00:00 expensidev php-cgi: NaLixC /index.php tyler@expensify.com !web! ?api? [info] …
```
=> Set default bedrock command timeout

src/Client.php
@tylerkaraszewski @iwiznia please review
https://github.com/Expensify/Expensify/issues/92336
We only want to retry time outs that weren't caused by long running queries. The latter will be thrown with a different message.
Ensured that ConnectionFailure is caught for `555 Timeout`. Ensured that exception bubbles up for any other `555 Timeout peeking command`, etc.
=> Only retry timeout that isn't from a SQLite query

src/Client.php
@flodnv will you please review this?
cc: @iwiznia
This PR adds a check to see if the current host config on a socket is still on the list of possible hosts before trying to send a request to that host. This should prevent us from getting empty Bedrock responses.
$ https://github.com/Expensify/Expensify/issues/89518
1. Created a request in Web-Expensify called `requestTest.php` that ran `ReportStore::getByID($_REQUEST['authToken], 144)`
1. Manually forced the host to be blacklisted after a successful request was made in Client.php
1. Logged into the website on dev
1. Loaded www.expensify.com.dev/requestTest.php
1. Tailed the logs and confirmed that the first request to the host was successful, that the host was then blacklisted, and that we hit log line indicating that it would not be …
=> Check for current host in list of possible hosts

src/Cache.php
@fnwbr please review
Needed to fix https://github.com/Expensify/Expensify/issues/92647
Tests:
```
>>> $c = Expensify\Bedrock\Client::getInstance()
=> Expensify\Bedrock\Client {#2511
+commitCount: null,
}
>>> $h = new Expensify\Bedrock\Cache($c)
=> Expensify\Bedrock\Cache {#2518}
>>> $h->read('caca')
=> [
"headers" => [
"commitCount" => "3833",
"nodeName" => "bedrock",
"peekTime" => "5319",
"totalTime" => "5428",
"unaccountedTime" => "79",
"Content-Length" => "0",
],
"body" => [],
"size" => 133,
"codeLine" => "404 No match found",
"code" => 404,
]
>>> $h->write('caca', 1)
=> [
"headers" => [
"Content-Length" => "0",
],
"body" => [],
"size" => 46,
"codeLine" => "202 Successfully queued",
"code" => 202,
]
```
Logs:
```
2018-11-14T11:46:31.100041+00:00 expensidev php: AIyIHx …
```
=> Make all cache commands idempotent

bin/BedrockWorkerManager.php
@iwiznia please review
More than once have I thought "Maybe this process is stuck since days, let's see what it is doing".... but the PID is never logged. Damn, I now realize it gets logged [here](https://github.com/Expensify/Bedrock-PHP/blob/8dbcbd8d873ce21c6baeb7c10650482827db2613/bin/BedrockWorkerManager.php#L401), but logging it here will make it more visible IMO (that's where I was looking at to find it) 😬 
Copied the code locally, watched logs
```
2018-11-19T14:25:18.467180+00:00 expensidev php: xZFwQx vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] Fork succeeded, child process, running job ~~ PID: '10235' name: 'www-prod/EmailNotification' id: '20' extraParams: ''
2018-11-19T14:25:18.481757+00:00 expensidev php: 0CGoty vendor/bin/BedrockWorkerManager.php …
```
=> Log PID of workers

bin/BedrockWorkerManager.php, composer.json
Change the if condition to confirm if a bedrock job is mock job by checking if the `mockRequest` parameter is `true` instead of `1`. 
$ https://github.com/Expensify/Expensify/issues/85244
1. Uncomment this [line](https://github.com/Expensify/Web-Expensify/blob/dc63631bde51cd4517b6dec8b0137767cd191089/www-dev-config.php#L4) in Web-Expensify
2. Start the bedrock worker manager and tail the logs for the remainder of the steps
3. Trigger a job through `Web-Expensify` (I did a ReportExporter job through IS)
4. Monitor the logs to verify that we created the job with `'mockRequest': 1`
5. After the job is completed, look for this log line to verify that we skipped [this section](https://github.com/Expensify/Bedrock-PHP/blob/master/bin/BedrockWorkerManager.php#L313) for the mocked job
=> Check for 1 and true in BedrockWorkerManager

composer.json, src/Client.php
When we moved over to FPM the version we are on doesn't include `getallheaders` so the call errors with an unknown function error.
Discovered apart of https://github.com/Expensify/Expensify/issues/95795 and discussion in #infra https://expensify.slack.com/archives/C094TGUTZ/p1546619668475300
I'm not 100% on changing this since we safe guard with `function_exists` and FPM PHP 7.3 does have `getallheaders`
=> Check $_server for mock request header

bin/BedrockWorkerManager.php, composer.json
If you add the versionWatchFile flag but the file doesn't exist, create it.
Part of https://github.com/Expensify/Expensify/issues/95570
1. Make sure version watch file doesn't exist
2. Run BWM with `--versionWatchFile=<file>` flag
3. Confirm that BWM runs
=> Create versionWatchFile if it doesn't exist

composer.json, src/Client.php
Tests:
Go to onsignin, check webrock logs contain email:
```
2019-01-16T16:33:59.047790+00:00 expensidev php-cgi: ICOQ4a /onsignin.php ionatan@expensify.com !web! ?api? [info] Bedrock\Client - Starting a request ~~ command: 'CreateJob' clusterName: 'webrock' headers: '[name: 'www-prod/ScrapeCards?accountID=1' data: '[accountID: '1' _commitCounts: '[auth: '14855']']' firstRun: '' repeat: '' unique: '1' jobPriority: '500' parentJobID: '' Connection: 'forget' idempotent: '1' retryAfter: '' requestID: 'ICOQ4a' lastIP: '10.2.2.1' writeConsistency: 'ASYNC' priority: '500' timeout: '290000' logParam: 'ionatan@expensify.com']'
2019-01-16T16:33:59.048281+00:00 expensidev php-cgi: ICOQ4a /onsignin.php ionatan@expensify.com !web! ?api? [info] Bedrock\Client - APC fetch host configs ~~ 0: 'localhost' …
```
=> Support logparam config

composer.json, src/Client.php
Fixes Expensify/Expensify#96880
Check that commitCount is correctly preserved for webrock in BWM.
The getInstance method uses the config passed and the default config to build a new instance of the Client or to return an existing one that has been built before that has the same configuration. When we added the `logParam` config, it broke this system in BWM, because we first configure it with logParam `null` and then we re-configure it with logParam as the email of the user that owns the job being run, that made it so it returned a new instance of the Client for each job, one that did not have the commitCount set correctly.
=> Remove logParam from getInstance method

composer.json, src/Client.php
@coleaeason please review
Related to Expensify/Expensify#70743 (comment)
Tests:
```
2019-01-24T13:27:34.834042+00:00 expensidev bedrock: xGChxM (BedrockCommand.cpp:286) finalizeTimingInfo [worker3] [info] command 'SetNameValuePair' timing info (ms): 5 (1), 0 (0), 0, 0, 0, 0, 5, 0, 0. Upstream: 0, 0, 0, 0.
2019-01-24T13:27:36.983074+00:00 expensidev php-cgi: xGChxM /caca.php ionatan@expensify.com !web! ?api? [info] Bedrock\Client - Request finished ~~ host: 'auth' command: 'SetNameValuePair' jsonCode: '200 OK' duration: '11' net: '5.619' wait: '5.381' proc: '0' commitCount: '14927'
```
=> Fix timing log

composer.json, src/Client.php
Fixes issues like what we see in [this request](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2202Mdtd%22)+AND+timestamp:%5B2019-01-23T14:41:11.607Z+TO+2019-01-23T16:41:11.607Z%5D&index=logs_expensify-001259)
Tests:
- Make a bedrock request during server shutdown
- Check Connection:close is returned by the server
- Check client disconnects from the server and establishes a new connection
=> Respect connection close coming from the server

composer.json, src/Client.php
@iwiznia 
Fixes: https://github.com/Expensify/Expensify/issues/96913
All this does is silence the warning here. We already handle the error case here with our retry logic exactly how we're supposed to, but we don't keep the warning from logging. Sometimes after `connect` returns `115`, we get this error. The retry should handle it correctly.
I'll update the version number if you agree with this change.
=> Silence built-in warning, we'll handle it

bin/BedrockWorkerManager.php, composer.json
We already attempt to catch if the job was retried elsewhere, so that would mean the jobID doesn't exist. The error name must've changed or something...
Part of https://github.com/Expensify/Expensify/issues/95570
=> Catch BWM crashing when jobID doesn't exist

composer.json, src/Client.php
@mattabullock Since we switched back to cloudflare we've been passing the wrong IP through to Bedrock for requests. This corrects that. 
Without a `X-Forwaded-For` header set:
```
2019-03-07T21:54:47.513599+00:00 expensidev php-fpm: kk53YW /api.php cole@expensify.com !web! ?api? [info] Bedrock\Client - Starting a request ~~ command: 'GetPartnerList' clusterName: 'auth' headers: '[email: 'cole@expensify.com' idempotent: '1' logParam: 'cole@expensify.com' requestID: 'kk53YW' lastIP: '10.2.2.1' writeConsistency: 'ASYNC' priority: '500' timeout: '290000']'
```
With `X-Forwarded-For` header set to `10.2.2.30`:
```
2019-03-07T21:54:43.529499+00:00 expensidev php-fpm: WRBteQ /api.php cole@expensify.com !web! ?api? [info] Bedrock\Client - Starting a request ~~ command: 'GetPartnerList' …
```
=> Use proxy IP if it exists

composer.json, src/Client.php
Attempts to fix the issue https://github.com/Expensify/Expensify/issues/69763
Holding to address any comments and create the new version.
Tests:
- Stop the auth server and make a request. Check it tries all possible hosts twice, the fails.
- Stop the auth server and make a request. Check it tries all possible hosts once, then start the server back up and check it finishes the request correctly.
- Modify code so that instead of ConnectionError it throws BedrockError, stop the auth server and make an idempotent request, check it tries to use all the hosts twice then fails.
- Modify code so that instead of ConnectionError it throws BedrockError, stop the auth server and make an idempotent request, check it tries to use all the hosts once, then start the server back and check it finishes the …
=> Retry in all hosts again if all hosts failed

composer.json, src/Jobs.php
@pecanoro, can you review this. 
We have a RequeueJobs method in Bedrock. This is just an intermediate function so that web-E can make use of that bedrock endpoint.
~On HOLD till this Bedrock [PR](https://github.com/Expensify/Bedrock/pull/643) gets merged.~
Helps with this [PR](https://github.com/Expensify/Web-Expensify/pull/24807) 
None
=> Adding a function to call our bedrock endpoint of RequeueJobs

composer.json, src/Client.php
This change allows for  Bedrock to return non-JSON data to PHP without PHP failing to parse it as JSON. This is being used for this: https://github.com/Expensify/Expensify/issues/103358 to pass a gzipped blob of scoring data back from Bedrock to PHP
=> Allow unparsed Bedrock responses to PHP

bin/BedrockWorkerManager.php, composer.json
@pecanoro please review
Did what I proposed [here](https://github.com/Expensify/Expensify/issues/100552#issuecomment-500845895).
Queue 2 jobs one with retry after and one without it
Modify bwm in order to fail the  finishJob call
Run bwm, check one of the jobs is in FAILED state and the other one in RUNQUEUED.
=> Do not call failJob when finishJob fails on retryAfter jobs

bin/BedrockWorkerManager.php, composer.json, src/Jobs.php
@iwiznia will you review this?
https://github.com/Expensify/Expensify/issues/95087
1. Started up BWM
1. Ensured that jobs were processing and running
1. Tailed the logs
1. `touch /var/tmp/ADMIN_DOWN`
1. Ensure jobs stop processing
1. Look for status in the logs:
```
2019-09-12T21:01:51.047036+00:00 expensidev php: SA0pNL vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] ADMIN_DOWN status detected. Not spawning more child processes. Trying again after 1s.
```
1. `rm /var/tmp/ADMIN_DOWN`
1. Ensure jobs start processing again
=> Add Admin Down Status Detection

.travis.yml
@coleaeason  will you please review this?
Setting the PHP "patch release" version number, to line up with apt-mirror, and see if travis can work with it.
related to https://github.com/Expensify/Expensify/issues/106963
Travis
=> adding patch level to php version number

.travis.yml, composer.json, src/Jobs.php
Adds in the `priority` parameter to match with the `jobPriority` parameter from `UpdateJobs`.
Bumping version to 1.8.4 
Corresponding Bedrock PR: https://github.com/Expensify/Bedrock/pull/691
Helps with https://github.com/Expensify/Expensify/issues/123018
=> Update Jobs to accept new `priority` parameter

composer.json
We did not bump the version [here](https://github.com/Expensify/Bedrock-PHP/pull/147), so doing it in this PR
=> Bump version to 1.8.7

composer.json, src/Jobs.php
Part of https://github.com/Expensify/Expensify/issues/143805
Adds overwrite parameter support for the `createJob` command.
Tests in https://github.com/Expensify/Web-Expensify/pull/29514
=> Add overwrite parameter support for createJob

.travis.yml
Run travis tests on both xenial and focal in preparation for upcoming Ubuntu 20.04 upgrade.
Part of Expensify/Expensify#137410
=> Run travis on xenial and focal

.travis.yml
This reverts commit 81adbb2243d24ed14d094dca382e62a67b659685.
As per [this comment](https://github.com/Expensify/Expensify/issues/137410#issuecomment-724841982), we've decided this isn't a valuable change for PHP repos.
=> Revert "run travis on xenial and focal"

bin/BedrockWorkerManager.php, composer.json
For https://github.com/Expensify/Expensify/issues/103058
Jobs named like `www-prod/Worker?email=something/@domain.com` don't run because we log `No worker found, ignoring ~~ jobName: 'www-prod/Worker'`. This fixes that
1. Reproduced locally by creating such a job with this name
2. Test again with the fix and see the job worker run
3. Ensure other job workers aren't affected by seeing them run as well
=> Fix running job names containing a '/' after the '?'

bin/BedrockWorkerManager.php
TL;DR: Logs the entire `RetryableException` when caught in `BedrockWorkerManager.php`.
This is useful so we can have more details about the `RetryableException` was thrown.
1. Create a bedrock job locally
1. In the bedrock job's `run` method, throw a `RetryableException` - pass some string into the first parameter of the exception
2. Example: see how it's being thrown in https://github.com/Expensify/Web-Expensify/pull/30574
2. Run the job, make sure the `RetryableException` gets thrown
3. See the exception data in the logs (search for `"Job could not complete, retrying"`, the exception's data should be shown nearby)
$ https://github.com/Expensify/Expensify/issues/159221
Discussion here: https://expensify.slack.com/archives/C03TQ48KC/p1617365746278500
=> Log RetryableException message

bin/BedrockWorkerManager.php, composer.json
We want to compare job names without query strings, or they all look different.
https://github.com/Expensify/Expensify/issues/177470
=> Make sure to strip query string parameters

bin/BedrockWorkerManager.php, composer.json
This is an experiment to see if we can detect when the type of job that we're processing changes, such that we can reset our targets for new job types. This doesn't do anything but log if it thinks the job type has switched. We'll deploy to production and watch for a few days to see if it correctly notices when the job type changes.
This is a follow-up to this PR which attempted the same thing but was far too noisy:
https://github.com/Expensify/Bedrock-PHP/pull/162
Issues:
https://github.com/Expensify/Expensify/issues/177470
=> Second "job profile swithcing" experiment

bin/BedrockWorkerManager.php, composer.json
This is a fix for the warnings seen here: https://expensify.slack.com/archives/C07J32337/p1632414804283600
As well as some other potential warnings.
Tested locally and verified it doesn't warn.
=> Fix warnings caused by previous change

bin/BedrockWorkerManager.php, composer.json
`$jobName` is already declared so we're overwriting it with the code that's removed here.
This is causing *only* the first run of jobs to work when starting BWM, then the name is getting re-assigned, and it fails to find any more jobs until it's restarted and thus resets the job name.
issue:
$ https://github.com/Expensify/Expensify/issues/179264
=> 'jobName' is already a variable

bin/BedrockWorkerManager.php, composer.json
More logging trying to figure out how to detect when the spikes here start:
https://github.com/Expensify/Expensify/issues/177470
Tested locally and seems to work fine:
```
2021-09-28T19:46:33.307481+00:00 expensidev2004 php: 1IXrYx vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [dbug] _send( expensidev2004.web.bedrock.jobs.GetJobs:8|ms )
2021-09-28T19:46:33.307667+00:00 expensidev2004 php: 1IXrYx vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [dbug] _send( expensidev2004.web.bedrockJob.call.response.GetJobs200:1|c )
2021-09-28T19:46:33.307737+00:00 expensidev2004 php: 1IXrYx vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] [AIMD] current jobs (running): ~~ fakeA: '1'
2021-09-28T19:46:33.313123+00:00 expensidev2004 php: 1IXrYx …
```
=> More BWM Logging

bin/BedrockWorkerManager.php, composer.json
Tests:
Created a job, run BWM, checked the log line
```
2021-10-12T19:04:33.303238+00:00 expensidev2004 php: ASItIC vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [dbug] _send( expensidev2004.web.bedrockJob.lateBy.www-prod/ScrapeCards:19000|ms )
```
=> Add lateBy metric for BWM

composer.json, src/Jobs.php
We add a new constant for job priority 0. Update all occurrences in Web-E and then update `PRIORITY_LOW` to 250.
Required for https://github.com/Expensify/Web-Expensify/pull/32667
Slack discussion https://expensify.slack.com/archives/C03TQ48KC/p1640954580274500
=> Add new constant for job priority

composer.json, src/Jobs.php
As we started supporting new job priorities, we need to add and update constants
It also reverts the constant added [here](https://github.com/Expensify/Bedrock-PHP/pull/176) as we lately decided to use constant names such as PRIORITY_0 and so.
Required for Expensify/Web-Expensify#32667
Slack discussion https://expensify.slack.com/archives/C03TQ48KC/p1640954580274500
=> Use new constants for job priorities

bin/BedrockWorkerManager.php, composer.json
See this slack thread: https://expensify.slack.com/archives/CQG20GM7X/p1654787619165049
Basically each thread needs a new seed so that they don't produce identical random numbers.
=> Re-seed random numbers with each new child PID

src/DB.php, src/Stats/NullStats.php
I had to do this to get the code working properly on my side project. Without this, it was throwing an exception "Unable to call method getCode() on Closure object" or something similar. Might have something to do with me using PHP 8.1? LMK if I'm holding it wrong.
=> store response object not closure

bin/BedrockWorkerManager.php, composer.json
Related with https://github.com/Expensify/Expensify/issues/229197
I did not find a way to find jobs that take forever to run, so I'm adding this log. Tested by adding a sleep in a job and running BWM, and checking logs:
```
2022-11-16T05:36:05.613501-06:00 expensidev2004 php-fpm: ubno3h vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [hmmm] Job took longer than 1 minute ~~ duration: '61.05256485939' name: 'www-prod/ScrapeCards'
```
=> Log when a job takes longer than 1 minute so it's easier to find them

.travis.yml
We're updating PHP to version 8.1.18 as part of QSP. This makes Travis use the new version for tests.
For https://github.com/Expensify/Expensify/issues/287532
Make sure Travis tests pass
No QA
=> [QSP] Update PHP version for Travis

.travis.yml
Simply bumps the Travis PHP version for QSP: https://github.com/Expensify/Expensify/issues/308605
=> Bump Travis for QSP

composer.json, src/Client.php
Only set the commitCount when we do a write, since when we just did a read there's no commit to be waiting for.
Context https://expensify.slack.com/archives/C05TD78MJH1/p1696527242392409?thread_ts=1696522633.446849&cid=C05TD78MJH1
Tests, you can see here a few commands that are not reads that receive but not pass a commitCount and every command after UpdateTransaction passing a commitCount:
```
2023-10-05T17:56:40.213106+00:00 expensidev2004 php-fpm: ddyyIH /api.php ionatan@expensify.com !web! ?api? [info] Bedrock\Client - Starting a request ~~ command: 'UpdateReport' clusterName: 'auth' headers: '[total: '-300' currency: 'USD' cachedData: '<REDACTED>' reportActionListCount: '4' connection: 'forget' authToken: '<REDACTED>' reportID: '5192450703871025' idempotent: '1' logParam: …
```
=> Only set the commitCount when we do a write

src/Client.php
$https://github.com/Expensify/Expensify/issues/323419
Missed the parenthesis when adding this here https://github.com/Expensify/Bedrock-PHP/pull/197 🤦 
See there for tests, but also: load https://www.expensify.com.dev/_utilities/dbStatus.php and check no warning or error appears
=> Need to enclose this in parens

.travis.yml
Update PHP for Travis to version 8.1.25 as per the instructions in the linked issue
https://github.com/Expensify/Expensify/issues/336493
=> Update travis PHP version

composer.json, src/Client.php
PHP when serializing to JSON will strip the `.0` of floats making them look like integers. Then, when we parse these JSONs in Auth, they are parsed as INT instead of FLOAT.
Found this issue investigating: https://github.com/Expensify/App/issues/32824
Asked in slack about it here: https://expensify.slack.com/archives/C03TQ48KC/p1704906489753899
Check that you can't reproduce the bug in https://github.com/Expensify/App/issues/32824 and verify the distance request is created correctly
cc @johnmlee101 @iwiznia
=> Use JSON_PRESERVE_ZERO_FRACTION

src/Client.php
cc @roryabraham @tylerkaraszewski 
Issue:
https://github.com/Expensify/Expensify/issues/328201
Discussion here: https://expensify.slack.com/archives/C03TQ48KC/p1704745068459599?thread_ts=1698081801.911129&cid=C03TQ48KC
Tests:
1. Before the change, the code ends up throwing an `ExpException` without retrying
2. After the change, the command gets retried as expected, and ends up throwing an `Expensify\Bedrock\Exceptions\ConnectionFailure` exception
=> Retry '500 Internal Server Error'

bin/BedrockWorkerManager.php, composer.json
cc @iwiznia while I dev noticed that this will break the `counter()` call as `$target` can be a float. 
Couldn't find any other obvious examples.
=> Ensure we are passing `int` not `float` for `StatsD::counter()` in BWM

composer.json, src/Client.php
Context: https://expensify.slack.com/archives/C07PP7QV8P5/p1733157297373329?thread_ts=1733154064.466989&cid=C07PP7QV8P5
While testing this I realized that passing priority was completely broken as it was always getting replaced with the normal priority.
=> Use passed priority if set instead of default

.github/workflows/bedrock-php.yml
For https://github.com/Expensify/Expensify/issues/469419
Updating the runners to use 24.04
=> Update GHA to use 24.04

.github/actions/composite/setup-composer-cache/action.yml, .github/workflows/bedrock-php.yml
Coming from https://expensify.slack.com/archives/CC7NECV4L/p1743022578963949, this pull request updates all mutable action references to use immutable commit hashes instead. This is a security measure to protect from supply chain attacks.
=> Pin GitHub Actions to immutable commit SHAs

composer.json, src/Client.php
Needed for https://github.com/Expensify/Expensify/issues/509923
Used in https://github.com/Expensify/Web-Expensify/pull/47169
=> Add microsecond timeouts to bedrock client

composer.json, src/Client.php
Looks like it made things worse, and we don't really understand why
https://expensify.slack.com/archives/C05CBC62HGW/p1754382926808129?thread_ts=1753963404.678779&cid=C05CBC62HGW
=> Revert changes from version 2.1.3

src/Client.php
In the related issue, we are logging differences between the report title that is calculated according to the custom formula by Auth and by Web Expensify. I am pretty sure that this is happening because Web Expensify is using stale report data when it computes the title and Auth is using up-to-date data. In order to be able to ignore these logs, we are going to include the commit count when the report was loaded and the commit count that Auth used when computing the title. With that information, we can easily see when the title would have been computed correctly if not for the fact that it is using stale data.
Currently Bedrock-PHP only saves the commitCount for write commands, but in order to keep track of the commitCount when reports are loaded, it needs to be saved for all report load …
=> Save commitCount when response says to
