src/Jobs.php
I'm not sure what the procedure is here, sooooooooooo
=> Add an optional repeat parameter to udpateJob()

README.md, composer.json
I forgot to bump this with my last change, and can't get the latest version installed without it.
=> Update composer.json to the latest version

composer.json, src/Client.php
This adds the ability to send a requestID to bedrock in order to get consolidated logging.
=> Add requestid

composer.json, src/Client.php
This adds the configuration option for bedrock's write consistency.
=> Add write consistency configuration

composer.json, src/Jobs.php
@pecanoro please review.
Adds constants for the priorities.
=> Add priority constants

bin/BedrockWorkerManager.php, composer.json
Fixes https://github.com/Expensify/Expensify/issues/50915
=> More randomness

bin/BedrockWorkerManager.php
Fixes https://github.com/Expensify/Expensify/issues/50915
=> More randomness on REQUEST_ID

composer.json, src/Jobs.php
@pecanoro please review
$ https://github.com/Expensify/Expensify/issues/54002
Tested requiring the class directly from the source on my VM and calling `getJobs` on it
```
vagrant-ubuntu-trusty-64 /git/expensify.com (carlos-ss) $ php -d display_errors=1 -a
Interactive mode enabled
php > require('/vagrant/Bedrock-PHP/src/Jobs.php');
php > $j = new \Expensify\Bedrock\Jobs(new \Expensify\Bedrock\Client());
php > $r = $j->getJobs('www-prod/SmartScan*', 3);
php > echo json_encode($r, JSON_PRETTY_PRINT);
{
"codeLine": "200 OK",
"code": 200,
"headers": {
"commitCount": "211",
"Content-Length": "745"
},
"rawBody": "{\"jobs\":[{\"data\":{\"receiptID\":205,\"filename\":\"w_e0bb16554c8586ac509d3bbef8c85f54af989c79.jpg\"},\"jobID\":58,\"name\":\"www-prod\\\/SmartScanAmountAndCurrency\",\"parentData\":{ …
```
=> Add getJobs to Jobs bedrock client lib

composer.json, src/Client.php, src/Jobs.php
@iwiznia please review
Also fix processTime in the headers
Tested by looking at logs for CreateJob requests
=> Log jobID after a job is created

composer.json
@iwiznia 
Fixes the composer version... 
- https://github.com/Expensify/Bedrock-PHP/compare/1.0.20...master
- https://github.com/Expensify/Bedrock-PHP/compare/flo_version...1.0.21
=> Increment composer version

composer.json, src/Jobs.php
@cead22 
$ https://github.com/Expensify/Expensify/issues/49377
$ https://github.com/Expensify/Expensify/issues/49375
```
php > require('/vagrant/Bedrock-PHP/src/Jobs.php');
php > $j = new \Expensify\Bedrock\Jobs(new \Expensify\Bedrock\Client());
php > $json = json_decode('[{"name":"testCreate", "data":{"blabla":"blabla"}, "repeat": "SCHEDULED, +1 HOUR"}, {"name":"testCreate2", "data":{"nope":"nope"}}]'); 
php > $r = $j->createJobs($json);
php > echo json_encode($r, JSON_PRETTY_PRINT);
{
"codeLine": "200 OK",
"code": 200,
"headers": {
"commitCount": "16157",
"peekTime": "4645",
"processTime": "3001",
"totalTime": "13458",
"Content-Length": "20"
},
"rawBody": "{\"jobIDs\":[108,109]}",
"body": {
"jobIDs": [
108,
109
]
}
}
php > $r = $j->getJob('testCreate');
php > $json = …
```
=> PHP functions for CancelJob and CreateJobs

bin/BedrockWorkerManager.php
When the database isn't created at the beginning due to the load handler being disabled, it was failing to write to it later because it didn't exist. This was never a problem with my testing because I didn't ever drop the table before testing, sorry about that.
https://github.com/Expensify/Expensify/issues/59068
1. Make sure /tmp/localJobsDB.sql doesn't exist
2. Create a bunch of jobs
3. Run BWM and confirm no write errors show up.
=> Only try to interface with DB if load handler enabled

composer.json
Update the build version in composer.json to the latest.
=> Update build version

composer.json, src/Client.php
@flodnv, will you please review this?
See last two commits of https://github.com/Expensify/Web-Expensify/pull/18023 - this is making Phan puke
None
=> Fix PHPdocs

bin/BedrockWorkerManager.php, composer.json, src/Client.php, src/Jobs.php
@flodnv please review. /cc @quinthar 
This implements the new failover code we talked about in https://github.com/Expensify/Expensify/issues/54343
See all tests in the [web PR](https://github.com/Expensify/Web-Expensify/pull/18557).
=> Improved failover code

composer.json, src/Client.php
Needed for Expensify/Expensify#54343
=> Add lastHost to bedrock client

composer.json, src/DB.php
@flodnv, @deetergp  please review.
Needed for https://github.com/Expensify/Expensify/issues/63431
=> Idempotent reads

src/Client.php
@flodnv please review. We were saving the commit count in the instance, so if you create several instances in the same request, you weren't sharing the commitCount.
See tests in web PR.
=> Fix commitCount param

composer.json, src/Client.php
@flodnv please review
If all our possible hosts are already blacklisted, then instead of failing immediately, use all possible hosts again.
=> Use all hosts when we have blacklisted all hosts already

.php_cs
Just like https://github.com/Expensify/PHP-Libs/pull/94
=> Update newline style rules

composer.json, src/DB.php, src/Exceptions/Timeout.php
This adds a timeout exception class.
Once you approve this or give a 👍  , I'll update the version number
Fixes https://github.com/Expensify/Expensify/issues/65018
Goes with https://github.com/Expensify/Web-Expensify/pull/19161/
=> Add a timeout exception

bin/BedrockWorkerManager.php, composer.json
@mattabullock 
I'll create the version once https://github.com/Expensify/Bedrock-PHP/pull/52 is merged
=> Catch Throwable, the new Exception superclass

composer.json, src/Client.php
@iwiznia 
Please review this change for 10x testing support. Please tell me if I need to change a version number somewhere.
=> Add support for 10x load testing

bin/BedrockWorkerManager.php, composer.json, src/Client.php
Fixes https://github.com/Expensify/Expensify/issues/66949
=> Fix retrying in failovers and BWM

src/Client.php
@flodnv please review /cc @tylerkaraszewski 
There isn't a new version because I was pushing it in the other PR before realizing you already merged it. I already deleted the previous tag and recreated it.
=> Only use getallheaders if is defined

composer.json, src/DB.php
Fixes https://github.com/Expensify/Expensify/issues/64613
Goes with https://github.com/Expensify/Web-Expensify/pull/19384
I'll update the version number when this is approved
=> Add timeout parameter to DB::run()

composer.json, src/Client.php
@flodnv please review
Fixes https://github.com/Expensify/Expensify/issues/67541
=> Retry bedrock commands if we didn't sent the full command out

bin/BedrockWorkerManager.php, composer.json
I misunderstood what timer/counter means in this context and realized it would be better to use timers.
1. Will test on staging
=> Change from counter to timer and fix type

bin/BedrockWorkerManager.php, composer.json
Related to https://github.com/Expensify/Expensify/issues/69840
=> Log times for updating local DB

.phan/config.php, ci/src/PHPStyler.php
@iwiznia, will you please review this?
Messed this up in https://github.com/Expensify/Bedrock-PHP/pull/77
=> Fix wrong path to php-style-fixer

composer.json, src/Client.php
=> Fix timing log

composer.json, src/DB.php
@iwiznia 
Tell me if anything looks wrong here.
=> Use ms instead of us timeouts.

bin/BedrockWorkerManager.php
Trying a different approach to the minimum dequeue jobs
=> Add minimum dequeue limit

composer.json, src/Client.php
@iwiznia please review. Resolves https://github.com/Expensify/Bedrock-PHP/pull/97#discussion_r186145280
=> Check if the preferred host exists in keys not in array

composer.json, src/Jobs.php
I am using the constant here https://github.com/Expensify/Web-Expensify/pull/21535/files#diff-1b31bee8fdcfb3a3a71485dcfb65511eR60
=> Add RUNQUEUED constant

README.md
Updating the readme to explain how to use commit hashes
=> Updating readme to use commit hashes

README.md, composer.json, src/Cache.php, src/Client.php, src/Exceptions/BedrockError.php, src/Exceptions/Cache/NotFound.php
Reverts Expensify/Bedrock-PHP#108 see https://github.com/Expensify/PHP-Libs/pull/175 on why.
It also modifies how the cache works a bit and adds some useful methods to it.
/cc @expensifyrandomdrake since you have a PR using the cache. Should not be much of a difference to you .
=> Update bedrock cache

composer.json, src/Client.php
`115 operation in progress` isn't a fatal error condition, so let's not treat it as such.
=> Ignore 115 errors

composer.json, src/Jobs.php
We need to add the retryAfter param to queueJob for an upcoming change on web. It already exists in CreateJob so we just need to accept the param and pass it through.
=> Add retryAfter to queueJob function

composer.json
Didn't add this in the last PR and then @flodnv had an itchy trigger finger on the merge.
=> Bump build version for retryAfter

composer.json, src/Client.php
Fix Scraping cards
Context https://expensify.slack.com/archives/C07J32337/p1548098546576600
=> Respect connection close

composer.json, src/Jobs.php
@iwiznia @mattabullock please review, HOLD til next week.
See https://github.com/Expensify/Expensify/issues/96492#issuecomment-458222951
- Logs before:
```
2019-01-29T14:16:04.575956+00:00 expensidev php: wdWH3x vendor/bin/BedrockWorkerManager.php florent@expensify.com !script! ?api? [info] Bedrock\Client - Starting a request ~~ command: 'CreateJobs' clusterName: 'webrock' headers: '[jobs: '[0: '[name: 'www-prod/ReportHarvester?reportID=3296' data: '[email: 'florent@expensify.com' reportID: '3296' policyID: '0427E44626699DFE' harvestingGUID: '0427E44626699DFE5c50602211493' violationsReportID: '3306' otherReportIDs: '[0: '3296' 1: '3153']' _commitCounts: '[webrock: '948' auth: '59725']']' unique: '1' parentJobID: '5324235749090413629']' 1: '[name: 'www-prod/ReportHarvester?reportID=3153' …
```
=> Call CreateJobs idempotently when it applies

bin/BedrockWorkerManager.php, composer.json
@mattabullock or @tylerkaraszewski please review
=> Remove AIMD1 in favor of AIMD2

bin/BedrockWorkerManager.php, composer.json
The same as [this PR](https://github.com/Expensify/Bedrock-PHP/pull/129) in a different spot.
=> Catch DoesNotExist error on FailJob

composer.json, src/Client.php
Fixed logging error when we were going to retry and changed a bit the code to do an early throw (you can best review the changes by looking at the 2 commits separately).
=> Do not log error if we are going to retry the command

composer.json, src/Client.php
@flodnv I realized I missed changing the log level when we retry ConnectionFailure errors
=> Do not log error if we are retrying

composer.json, src/Cache.php
@joelbettner please review. 
Needed for https://github.com/Expensify/Expensify/issues/105596
Check tests in web PR
=> Add headers to cache write

composer.json, src/Jobs.php, src/Plugin.php
See https://github.com/Expensify/Bedrock/pull/787
Needed for https://github.com/Expensify/Expensify/issues/131012
Will be testing this PR with the accompanying web PR. Please review this even in draft form, I will remove draft when I finish testing in web.
=> Add priority param to retryjob method

composer.json, src/Jobs.php
Hold https://github.com/Expensify/Bedrock/pull/799
Needed for Expensify/Expensify#131401
Tests in the web PR
=> Allow to pass nextRun in update job

.travis.yml, composer.json, composer.lock
Looks like everything is in working order. Gotta see if Travis passes, then we should be good to go here.
=> Update PHP version to 7.4.3 and update php fixer

bin/BedrockWorkerManager.php, composer.json, src/Stats/StatsInterface.php
`bedrockWorkerManager.numberOfJobsToQueue` is using the wrong value for the metric, it's duplicating the target. PR is to fix that.
=> Fix jobs to queue metric

.travis.yml
=> Lock composer version

.travis.yml
https://expensify.slack.com/archives/C03TQ48KC/p1608568663126800?thread_ts=1608564163.121900&cid=C03TQ48KC
=> Run Travis on 7.4.13

.travis.yml
Updating travis' PHP version for Quarterly Server Patching
=> updating php for travis

bin/BedrockWorkerManager.php, composer.json
Related to https://github.com/Expensify/Salt/pull/9819
=> Add more AIMD logs

bin/BedrockWorkerManager.php, composer.json
Related with https://expensify.slack.com/archives/C094TGUTZ/p1631632393287900?thread_ts=1631614714.235700&cid=C094TGUTZ
=> Fix stats call timer->counter

bin/BedrockWorkerManager.php
This is a fairly basic attempt at detecting when the bedrock job profile switches from one job type to anthoer. It doesn't do anything yet, except log that it's noticed a switch. If this proves to detect switching job profiles fairly accurately, we can use it to reset the job target, otherwise we can iterate on this.
I will update the tags for the library version once I have an approved code review to avoid doing that several times.
Issue:
https://github.com/Expensify/Expensify/issues/177470
Tests:
Tested locally and validated logs like:
```
2021-09-14T19:55:11.282663+00:00 expensidev2004 php: xKJNcs vendor/bin/BedrockWorkerManager.php we@dont.know !script! ?api? [info] [AIMD] job type switched from none to fakeA with 7 of 10 jobs selected.
2021-09-14T19:56:11.483003+00:00 expensidev2004 …
```
=> Detecting job profile switching

composer.json
=> Increment version

bin/BedrockWorkerManager.php, composer.json
Explanation here: https://expensify.slack.com/archives/C094TGUTZ/p1631787507041800?thread_ts=1631783921.038500&cid=C094TGUTZ
Tested live. 
Related with https://github.com/Expensify/Expensify/issues/177467
=> Sleep less when waiting to queue more jobs so that we gather better data

.travis.yml
- For QSP https://github.com/Expensify/Expensify/issues/159016
- See https://stackoverflow.com/c/expensify/questions/6258
- Also for https://github.com/Expensify/Expensify/issues/179249
=> Updating php and ubuntu version for travis

bin/BedrockWorkerManager.php, composer.json, src/Exceptions/Jobs/RetryableException.php, src/Jobs.php
cc @iwiznia 
Needed for https://github.com/Expensify/Expensify/issues/158814
Adds support for the new ignoreRepeat parameter. Also makes BedworkWorkerManager use it. 
Tests in https://github.com/Expensify/Web-Expensify/pull/32496
=> Add support for the ignoreRepeat parameter

.travis.yml
Part of https://github.com/Expensify/Expensify/issues/190250
=> Update php version for 2022 q1 qsp

.travis.yml
Part of https://github.com/Expensify/Expensify/issues/204734
travis 
no
=> Upgrade Travis to php 7.4.29

.travis.yml
https://github.com/Expensify/Expensify/issues/216938
=> version bump php

.travis.yml
- For https://github.com/Expensify/Expensify/issues/249892
- QSP issue https://github.com/Expensify/Expensify/issues/231401
=> Update travis php version

composer.json
forgot this in https://github.com/Expensify/Bedrock-PHP/pull/200
=> release 2.0.4

composer.json
Redo of https://github.com/Expensify/Bedrock-PHP/pull/201
Did I do this right this time? https://github.com/Expensify/Bedrock-PHP/blob/2.0.5/composer.json#L5
=> release 2.0.5

composer.json
Updating for https://github.com/Expensify/Bedrock-PHP/pull/209
See https://expensify.slack.com/archives/C094TGUTZ/p1715092938310149
cc @marcaaron
=> Update version to 2.0.9

.travis.yml
Part of https://github.com/Expensify/Expensify/issues/402521
=> Update PHP version for qsp

.github/workflows/bedrock-php.yml
Part of https://github.com/Expensify/Expensify/issues/459040
I'm not sure about this one because this is the only PR that requires a major bump. @johnmlee101
=> Update PHP version to 8.3.15 for QSP

.github/workflows/bedrock-php.yml
Part of https://github.com/Expensify/Expensify/issues/459040
=> [HOLD]  Update PHP version for QSP to 8.1.31

.github/workflows/bedrock-php.yml
Part of https://github.com/Expensify/Expensify/issues/498249
Automated, GH actions should be passing.
No QA.
N/A
=> Update PHP version for GH actions

bin/BedrockWorkerManager.php, composer.json, composer.lock, src/Client.php, src/LocalDB.php
For https://github.com/Expensify/Expensify/issues/504372
=> Remove useless logs

composer.json
I didn't know about the instructions in the readme for how to deploy my last PR [Save commitCount when response says to](https://github.com/Expensify/Bedrock-PHP/pull/232#top). Now I'm bumping the version number and pushing a tag for it.
https://github.com/Expensify/Expensify/issues/540370
=> Deploy save commit count feature

.github/PULL_REQUEST_TEMPLATE.md
The repo doesn't have a PR template, and it's easy to miss the instructions for how to ensure PRs here are deployed.
N/A, but I missed the deploy instructions recently, so this should help myself or others in the future.
=> Add PR template with deployment checklist item
